apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RZbTlpTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBeUFYYmpOakVtYU10aW1OdHV2Z1BWeU45L29iNEZwOWlqb1RuMDRndmtQK0s2c09GCjhZdzFtbHFPQjJQOEZiZFNwTnFEY1IxUGhvY0hiZmh3WmxRVHp0enRBdHZhV0RLN0JsdUkwUVp2SjNreHZJdkgKQzVWM2g0VmowWEFQM1ZTK3UwUmw2dGU1bkluN3pBbjA4a1NkVStLMVg2VkVtbXBTZlBha1VEb21vblJyUUt6Mwp1RnkvRmlVck5hZjAxOXFISXBaNTV5bGVuZCtQcmd3eHpNTWxNc0pWcjk1K3dVNm1wckJZNGNtVFc2R0dMYVM0CjBva0t4eXJ6RWVZVkxoR3JPSmVDTnFkUnpYWmc5c2JLNXJadG4wQVUxVUVQaHpPRTBsLzZtRmdlckM0WVFEVFUKelViY2VZUUJYYzNPNWRLOXJUeFY2ZlpCRHZKOVpYM1FRQ2ZMYXdJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFKdHNxSWRXMkpKVGI0MHNTSlpRNG5iZWpjdkNINWJ6K0JLUGJBSEpITWVuWk04Sng1NnIySisyCjZrKzhrSTNKVFdxbE9yTjVmOHVFVGU2ZnBERDNGc1VJRkl1T3B4djFIa0JOSlpiNmh2MWd2V0ZGOGRQTDBZT1gKaHA3WTgzOGM5aXJidVVYRUFaK2FCdFZvcWtWL0NMSHdNWkZRSkpKRnFvNVBLc01qSDVrSFFBcjV0d3BqVXNrTApNYzVPUGdPcHVqNWpDTlB5dlNhcjVFdE11bXhLU1pGSnArZkprRDJOUDA5b1VJZGNadXVHZ1ZYaldFSTNPVlMrCmtVUG95QUhZNGRnWGRyeExNNyt4VGZ0bXZvd2FvZXE4Y09tNDgzbzh0L1ZjVGs1cVYyOVlmbjdqWXpRcTFWNEoKWWtxcEtmME5sSjdIRzJ4YUVWL0ZKMmtuV0FlR25HRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
